### ISSUE TITLE
Multiple GPUs support

### ISSUE THREAD

**Issue by oyxhust** [kazuto1011/grad-cam-pytorch#13]
It is a great job! However, I find that there have some problems when using multiple gpus.
When using DataParallel, like 'model = torch.nn.DataParallel(model)', it gets errors when using more than one gpu. The error appears in 'id(module)' in 'forward_hook' and 'backward_hook' do not match the 'id(module[1])' in '_find' function. But they are matched when using one gpu. Could you help to find the reason?

**Comment by kazuto1011** [comment]
Thank you for reporting this issue. Sorry I have no idea to fix it right now.
~Instead, PR #14 changed the hook functions so that now you can use on multiple GPUs.~

Sorry again, I found the PR #14 has another issue with `nn.DataParallel`. The forward/backward hooks are separately called on each GPU and the `_find` function cannot aggregate all instances in the mini-batch with the query `target_layer`. I think adding device id to the featuremaps/grads dictionaries may handle the problem, like:

```py
def forward_hook_(module, input, output):
    # Assume nested dictionary
    self.fmap_pool[key][module.device] = output.detach()
```

Then you can concatenate the values across the devices and make visualizations. I think the `nn.DataParallel` option may complicate the code. Let me keep it to make simple and readable for now.

**Comment by spetryk** [comment]
Hi, thanks for your help on this issue, I had the same problem. I implemented your suggestion to concatenate values across the multiple GPUs.

However, my reason for using multiple GPUs in the first place was due to a memory bottleneck - I want to train with a larger batch size and so spread out the computation. When I aggregate all the values onto one GPU, I run into out of memory errors in the backpropagation step.

Do you have any suggestions for how to get around this?
